name: London Prep

on:
  schedule:
    - cron: '25 6 * * *'   # 06:25 UTC

jobs:
  prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Send prep package
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT:  ${{ secrets.TELEGRAM_CHAT }}
        run: python prep_report.py
