name: Run Prep Report

on:
  schedule:
    - cron: '30 6 * * *'  # Run at 06:30 UTC every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install TA-Lib
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib/
        ./configure --prefix=/usr
        make
        sudo make install
        cd ..
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run prep report
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
      run: python prep_report.py 