name: Run Prep Report

on:
  schedule:
    - cron: '30 6 * * *'  # Run at 06:30 UTC every day
  workflow_dispatch:  # Allow manual triggering

jobs:
  run-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Check environment variables
      run: |
        if [ -z "${{ secrets.TELEGRAM_TOKEN }}" ]; then
          echo "ERROR: TELEGRAM_TOKEN is not set"
          exit 1
        fi
        if [ -z "${{ secrets.TELEGRAM_CHAT }}" ]; then
          echo "ERROR: TELEGRAM_CHAT is not set"
          exit 1
        fi
        echo "Environment variables are set"
        
    - name: Run prep report
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
      run: |
        echo "Starting prep report..."
        python prep_report.py
        echo "Prep report completed" 