name: Run Telegram Bot

on:
  schedule:
    - cron: '30 6 * * *'  # Runs at 06:30 UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-telegram-bot requests pandas matplotlib mplfinance
        
    - name: Run bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT: ${{ secrets.TELEGRAM_CHAT }}
      run: python prep_report.py 